# ⚠️  Ne pas committer avec les vraies valeurs !
# Créer avec : kubectl apply -f secret.yaml -n cine-memo
apiVersion: v1
kind: Secret
metadata:
  name: cinememo-secrets
  namespace: cine-memo
type: Opaque
stringData:
  DATABASE_URL: "postgresql://cinememo:CHANGE_ME@postgres.cine-memo.svc.cluster.local:5432/cinememo"
  NEXTAUTH_SECRET: "CHANGE_ME_GENERATE_WITH_openssl_rand_base64_32"
  NEXTAUTH_URL: "https://cine-memo.sl-information.fr"
  TMDB_API_KEY: "CHANGE_ME"
  GROQ_API_KEY: "CHANGE_ME"
  POSTGRES_PASSWORD: "CHANGE_ME"
