# ⚠️  Ne pas committer avec les vraies valeurs !
# Créer avec : kubectl apply -f secret.yaml -n boozeboard
apiVersion: v1
kind: Secret
metadata:
  name: boozeboard-secrets
  namespace: boozeboard
type: Opaque
stringData:
  NEXT_PUBLIC_SUPABASE_URL: "https://jebsjterbynzyxfcmcli.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "CHANGE_ME"
